version: "3"
networks:
  multiplayerBackend:

services:
  server:
    networks:
      - multiplayerBackend
    build: ./services/server
    environment:
      PORT: 3000
    ports:
      - 3000:3000
      - 2657:2657